### ISSUE TITLE
PA Review: Photos

### ISSUE THREAD

**Issue by katrinalui** [katrinalui/shuttr#10]

**Comment by debsfong** [comment]
Wow! This is great! In the interest of time, I will mark this MVP as done. However, I would like a way to view all of the photos I've uploaded if you have time at the end. (<-- Not part of MVP, just feels like it's missing)

**Comment by katrinalui** [comment]
Thanks, Debra! I have my routes and controller set up for a user show page, but I decided to move onto the next MVP so I don't fall behind. I would definitely like to create a user profile page that displays all of the users photos and albums!
